# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'дом', 'verbose_name_plural': 'дома'},
        ),
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(max_length=50, verbose_name='названиe'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.IntegerField(verbose_name='цена'),
        ),
    ]
